config:
    target: "wss://localhost:7000/websocket"
    phases:
      - duration: 20
        arrivalRate: 10
    ws:
      # Ignore SSL certificate errors
      # - useful in *development* with self-signed certs
      rejectUnauthorized: false
  scenarios:
    - engine: "ws"
      flow:
        - send: "hello"
        - think: 1
        - send: "world"
